kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kfechter/portfolio-site
    tags:
    - latest
    build_args_from_env:
     - FROM_EMAIL
     - RESEND_KEY
  environment:
    FROM_EMAIL:
      from_secret: from_email
    RESEND_KEY:
      from_secret: resend_key